### PR TITLE
move transform from <svg> to parent <g> (PS/PDF file clipping)

### LINKED ISSUE #178: PS/PDF clipping with overflow='hidden' renders incorrectly in Chromium/Chrome-based browsers
The new method of clipping embedded PS and PDF files (commit c6f7709) does not render correctly in Chromium-based browsers. The reason is that they ignore the `transform` attribute in `<svg>` elements. In fact, `transform` is not a valid attribute of the `<svg>` element, according to  https://www.w3.org/TR/SVG11/struct.html#SVGElement. 

On the other hand, Firefox takes it into account: `transform` is listed as a Presentation Attribute in https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg.

Test file:

````latex
\special{papersize=210mm,297mm}

x\hbox to 52bp{%
  \vrule width 0pt height 52bp%
  \special{pdffile="example.pdf" llx=10 lly=10 urx=62 ury=62 clip}\hss}x

\bye
````

[example.pdf](https://github.com/mgieseki/dvisvgm/files/8133836/example.pdf)

### PR DESCRIPTION
**Pull request by agrahn**
This moves the `transform` attribute from an `<svg>` element to a parent `<g>` element. Fixes #178 .

### CODE REVIEW

**Comment by mgieseki** [comment]
Thanks for digging into the code and for providing a fix for this issue. I'd prefer a variant that fixes the issue locally with the `svg` element. The following patch wraps this element with a group that gets the `transform` attribute if necessary. So far it seems to work as expected.

```diff
diff -r 77da1159cd08 src/PsSpecialHandler.cpp
--- a/src/PsSpecialHandler.cpp	Wed Feb 23 14:59:06 2022 +0100
+++ b/src/PsSpecialHandler.cpp	Thu Feb 24 17:07:01 2022 +0100
@@ -426,13 +426,15 @@
 			node = util::make_unique<SVGElement>("g");
 		else {
 			// clip image to its bounding box if flag 'clip' is given
-			node = util::make_unique<SVGElement>("svg");
-			node->addAttribute("overflow", "hidden");
-			node->addAttribute("x", bbox.minX());
-			node->addAttribute("y", bbox.minY());
-			node->addAttribute("width", bbox.width());
-			node->addAttribute("height", bbox.height());
-			node->addAttribute("viewBox", bbox.svgViewBoxString());
+			auto svg = util::make_unique<SVGElement>("svg");
+			svg->addAttribute("overflow", "hidden");
+			svg->addAttribute("x", bbox.minX());
+			svg->addAttribute("y", bbox.minY());
+			svg->addAttribute("width", bbox.width());
+			svg->addAttribute("height", bbox.height());
+			svg->addAttribute("viewBox", bbox.svgViewBoxString());
+			node = util::make_unique<SVGElement>("g");
+			node->append(std::move(svg));
 		}
 		_xmlnode = node.get();
 		_psi.execute(
```

**Comment by agrahn** [comment]
Thank you @martin, I have to apologise for not having tested enough the new clipping method recently. It was only today that a stumbled across the issue when I accidentally opened a test file in Chromium.

**Comment by mgieseki** [comment]
Alex, there's no need to apologize. I really appreciate your input on dvisvgm. Maybe I should add some kind of a validity check that detects malformed SVG files automatically.

**Comment by agrahn** [comment]
Thank you, Martin, for fixing this!

**Pull request closed without merging**
