### PR TITLE
Add missing <cstdint> includes for GCC 13

### PR DESCRIPTION
**Pull request by thesamesam**
Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by mgieseki** [comment]
Thank you for providing the fix. Could you please remove the includes from the `.cpp` files where `#include <cstdint>` is already present in the corresponding header? I'd prefer not to duplicate them.

**Comment by thesamesam** [comment]
Yep, sure, let me do that now.

**Review by mgieseki — APPROVED** [review]

**Comment by mgieseki** [comment]
Thank you for the update.

**Comment by thesamesam** [comment]
And thank you!

**Pull request merged**
